### ISSUE TITLE
[D2] 6.1 Activity Diagram

### ISSUE THREAD

**Issue by yi-kiat** [yi-kiat/ICT2106_P3-5#100]
TODO: Activity Diagram

To be completed on 30/3/2023

**Comment by jiaxinlarhh** [comment]
![Image](https://user-images.githubusercontent.com/92164522/226103065-25ae4efc-fa99-40c5-b81c-936feef2688e.png)

**Comment by jiaxinlarhh** [comment]
An activity diagram is used to show the flow of adding a resource form, linking it from the view and search feature. It is assumed that the regional manager is already logged in and is currently on the View Resource Form History page. The regional manager will start by viewing all the forms, then searching and filtering for a specific form. If the form does not exist, the user can add the form and then fill it out. The user has to fill in all the checkboxes and provide descriptions and additional comments before submitting the form. Upon submitting the form, the system will validate the input. If there is an error, the system will provide feedback with an error message; otherwise, it will return to the Resource Form History page, where the system will display historical records about the form, and the feature will end.

**Comment by AiXin18** [comment]
Review and closed on: 27/3/2023
